extends Node

signal blue_switch_toggle_on
signal blue_switch_toggle_off
signal star_collected
signal capability_unlocked_fart
signal spend_fuel
signal update_fuel_remaining
signal player_pipe_collision
